### ISSUE TITLE
Timing issues when file first opens

### ISSUE THREAD

**Issue by theKidOfArcrania** [creativitRy/ClearComposer#11]
Sometimes when we open a file, the first few notes are either too fast or too slow to come up.

**Comment by creativitRy** [comment]
This might be due to the lag spike you get when opening the midi synthesizer. A potential fix would be to wait for it to open and start playing then.

**Comment by theKidOfArcrania** [comment]
Or it could also originate from bad timings when we first configured tempo in AnimationTimer thingy?
