### ISSUE TITLE
Associate ccp as extension in registry and add drag and drop opening support

### ISSUE THREAD

**Issue by creativitRy** [creativitRy/ClearComposer#12]
needs an installer

**Comment by theKidOfArcrania** [comment]
Not necessary, but an installer might make it easier

**Comment by theKidOfArcrania** [comment]
Yeah sorry for modifying it three times, but I think the second part of the issue can easily be used using JavaFX's drag-and-drop API.

**Comment by theKidOfArcrania** [comment]
The file assocation is done for windows
