### ISSUE TITLE
Toggle Perma/Toggle

### ISSUE THREAD

**Issue by theKidOfArcrania** [creativitRy/ClearComposer#13]
These are two different modes (if I presume correctly), Perma and Toggle, where Perma Mode lets you left-click/right-click to turn on/ off a note as compared to Toggle mode where you click on a note to toggle it once.

**Comment by creativitRy** [comment]
Perma decides whether the notes entered will stay permanently or get turned off once played.
Toggle decides whether to input notes using left click for on/off or left for on and right for off.

**Comment by theKidOfArcrania** [comment]
Ahhh I see, should each note have like some sort of color to determine whether or not if the note is perma or not?

**Comment by creativitRy** [comment]
no but we can fix that
