### ISSUE TITLE
Chord progressions and maybe even melody line?

### ISSUE THREAD

**Issue by theKidOfArcrania** [creativitRy/ClearComposer#20]
Somehow, the melody and chord progression line would have to scroll somehow or something and the harmony chord lines would have to change along with it... not sure how it might be done.

**Comment by creativitRy** [comment]
You're thinking too much of a DAW here. I meant to create a repetitive music sequencer that is easy to use, not a full composition software (these already exist)

**Comment by creativitRy** [comment]
Another way of doing it is maybe adding a chord progression queue where the user can push in a chord and every time the 16 notes/12 notes repeat, the first one in the queue gets polled and used.

**Comment by theKidOfArcrania** [comment]
Yeah I guess you are right: it might be way too much

**Comment by theKidOfArcrania** [comment]
I think this is resolved with the intime chord progressions with issue #29
