### ISSUE TITLE
Chord suggestions

### ISSUE THREAD

**Issue by theKidOfArcrania** [creativitRy/ClearComposer#23]
based on past chords, suggest the best chord to transition to. Reference: http://learnhowtowritesongs.com/interactive-chord-progression-generator/

**Comment by creativitRy** [comment]
refer to getPossibleChordProgressions(Chord from) method in ChordProgressionHelper. https://github.com/creativitRy/ClearComposer/blob/master/src/main/java/com/ctry/clearcomposer/music/ChordProgressionHelper.java
