### ISSUE TITLE
Undo Redo buttons improvements

### ISSUE THREAD

**Issue by creativitRy** [creativitRy/ClearComposer#24]
They should become disabled (unable to be clicked and showing grayscale image) if there are no more undo/redo available. Also they should use the operation's toString() method for the tooltip and the display in the edit menu.

**Comment by theKidOfArcrania** [comment]
Yeah we need new icons for that

**Comment by theKidOfArcrania** [comment]
Would the tooltips on toolbar be necessary if the toString operation is used in the respective menu buttons?
