### ISSUE TITLE
Chords in time with beat

### ISSUE THREAD

**Issue by theKidOfArcrania** [creativitRy/ClearComposer#29]
Have the chords play in time with the beat so that the user can click the chord in advance and then don't have to get as good timing

**Comment by creativitRy** [comment]
maybe a dropdown box that matches chords to these options:
change every note
change every 2 notes
change every 3 notes
change every 4 notes
change every half a measure
change every measure

**Comment by theKidOfArcrania** [comment]
This is completed.
