### ISSUE TITLE
Change icons for Toolbar

### ISSUE THREAD

**Issue by theKidOfArcrania** [creativitRy/ClearComposer#6]
Uhmm... @creativitRy, the icons that you provided were not exactly the best for our usage...

**Comment by creativitRy** [comment]
will work on these at home

**Comment by creativitRy** [comment]
buttons needed are: ~~new file, open file, save file, play, pause, stop~~, toggle perma, toggle toggle, ~~button to change key, button to change "tempo", button to change time signature (12 notes or 16 notes).~~
~~don't have time to add undo/redo~~

**Comment by theKidOfArcrania** [comment]
Wait we still need Toggle perma and Toggle toggle
